spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: els_db_user
    password: H1@Y7A42g#Oo@s%gwf99#yWmfJih%G1wwUHM
    url: jdbc:mysql://gz-cdb-cvuqoqsl.sql.tencentcdb.com:61663/sc_sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.1.6
    port: 5672
    username: guest
    password: guest
#   redis:
#     host: 192.168.1.6
#     port: 6379
env:
  test
girl:
  name: mo
  age: 17
# feign:
#   client:
#     config:
#       default:
#         connectTimeout: 5000
#         readTimeout: 5000
#         loggerLevel: basic  