spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: els_db_user
    password: H1@Y7A42g#Oo@s%gwf99#yWmfJih%G1wwUHM
    url: jdbc:mysql://gz-cdb-cvuqoqsl.sql.tencentcdb.com:61663/sc_sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.1.6
    port: 5672
    username: guest
    password: guest
#   redis:
#     host: 127.0.0.1
#     port: 6379
girl: 
  name: hhm
  age: 23
env:
  dev3